---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver-svc
  namespace: demo-rest-trama
  labels:
    app: tcpserver-svc
spec:
  ports:
  - name: socket
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: tcpserver-pod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcpserver-configmap
  namespace: demo-rest-trama
data:
  LOG_LEVEL: "DEBUG"
  PORT: "9000"
  HOST: "127.0.0.1"
  DELAY_RANDOM_ENABLED: "true"
  DELAY_MAX: "2000"
  DELAY_MIN: "100"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver-deployment
  namespace: demo-rest-trama
  labels:
    app: tcpserver-deploy
spec:
  selector:
    matchLabels:
      app: tcpserver-pod
  replicas: 1
  template:
    metadata:
      name: tcpserver-pod
      namespace: demo-rest-trama
      labels:
        app: tcpserver-pod
    spec:
      containers:
        - name: tcpserver-contenedor
          image: quay.io/ivanstalyn/tcpserver:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 3m
              memory: 96Mi
          envFrom:
          - configMapRef:
              name: tcpserver-configmap
